# coding=utf-8
"""Editor waveform peaks are generated by a job and served from a bounded cache.

The peaks GET used to run ffmpeg over the whole audio track inside the request.
Now it answers from the cache, or queues one job per media file and track and
answers 202 with that job's id. A second request while the job runs follows the
same job instead of starting another ffmpeg.
"""
import json
import os
import shutil
import subprocess

import pytest
from flask import Flask

from api.editor import editor as editor_api
from app import jobs_queue as jobs_queue_module
from utilities import job_dedupe, waveform_peaks

needs_ffmpeg = pytest.mark.skipif(not shutil.which('ffmpeg') or not shutil.which('ffprobe'),
                                  reason='ffmpeg and ffprobe are required')


@pytest.fixture
def queue(monkeypatch, tmp_path):
    fresh = jobs_queue_module.JobsQueue()
    monkeypatch.setattr(jobs_queue_module, 'event_stream', lambda **kwargs: None)
    for module in (waveform_peaks, job_dedupe):
        monkeypatch.setattr(module, 'jobs_queue', fresh)
    # Leave the job pending so the tests decide when it runs.
    started = []
    monkeypatch.setattr(fresh, 'force_start_pending_job', started.append)
    fresh.started = started
    monkeypatch.setattr(waveform_peaks, 'PEAKS_CACHE_DIR', str(tmp_path / 'cache' / 'peaks'))
    return fresh


def _run(queue, job_id):
    job = next(job for job in queue.jobs_pending_queue if job.job_id == job_id)
    queue.jobs_pending_queue.remove(job)
    queue.jobs_running_queue.append(job)
    queue._run_job(job)
    return job


def _media(tmp_path, name='film.mkv', audio=True):
    path = tmp_path / name
    inputs = ['-f', 'lavfi', '-i', 'color=c=black:s=64x64:d=3']
    if audio:
        inputs += ['-f', 'lavfi', '-i', 'sine=frequency=440:duration=3']
    subprocess.run(['ffmpeg', '-v', 'error', '-y', *inputs, '-shortest', str(path)], check=True)
    return str(path)


def test_a_missing_waveform_is_queued_once_per_file_and_track(queue, tmp_path):
    video = tmp_path / 'film.mkv'
    video.write_bytes(b'not really a film')

    state, job_id = waveform_peaks.request_peaks(str(video), 0)
    again, same = waveform_peaks.request_peaks(str(video), 0)
    _, other_track = waveform_peaks.request_peaks(str(video), 1)

    assert (state, again) == ('queued', 'queued')
    assert same == job_id
    assert other_track != job_id
    jobs = queue.list_jobs_from_queue()
    assert len(jobs) == 2
    assert jobs[0]['job_name'] == 'Generating waveform for film.mkv'
    assert jobs[0]['module'] == 'utilities.waveform_peaks'
    assert jobs[0]['is_progress'] is True
    # The editor waits on it, so it is started rather than left behind a scan.
    assert queue.started[:2] == [job_id, job_id]


def test_a_running_job_is_followed_rather_than_repeated(queue, tmp_path):
    video = tmp_path / 'film.mkv'
    video.write_bytes(b'x')
    _, job_id = waveform_peaks.request_peaks(str(video), 0)
    job = queue.jobs_pending_queue.popleft()
    queue.jobs_running_queue.append(job)

    assert waveform_peaks.request_peaks(str(video), 0) == ('queued', job_id)
    assert len(queue.list_jobs_from_queue()) == 1


@needs_ffmpeg
def test_the_job_writes_the_cache_that_the_next_request_serves(queue, tmp_path):
    video = _media(tmp_path)
    _, job_id = waveform_peaks.request_peaks(video, 0)

    job = _run(queue, job_id)

    assert job.status == 'completed'
    state, data = waveform_peaks.request_peaks(video, 0)
    assert state == 'ready'
    assert data['sampleRate'] == 10
    assert 2.5 < data['duration'] < 3.5
    assert 25 <= len(data['peaks']) <= 35
    assert max(abs(peak) for peak in data['peaks']) == 1
    assert len(queue.list_jobs_from_queue()) == 1
    assert os.listdir(waveform_peaks.PEAKS_CACHE_DIR) == [os.path.basename(
        waveform_peaks.peaks_cache_file(video, 0))]


@needs_ffmpeg
def test_a_file_without_that_audio_track_fails_the_job_with_the_reason(queue, tmp_path):
    video = _media(tmp_path, audio=False)
    _, job_id = waveform_peaks.request_peaks(video, 0)

    job = _run(queue, job_id)

    assert job.status == 'failed'
    assert job in queue.jobs_failed_queue
    assert not os.path.isdir(waveform_peaks.PEAKS_CACHE_DIR) or not os.listdir(waveform_peaks.PEAKS_CACHE_DIR)
    with pytest.raises(waveform_peaks.JobFailed, match='could not read audio track 1'):
        waveform_peaks.generate_waveform_peaks(video, 0)


def test_a_file_that_disappeared_fails_with_the_reason(queue, tmp_path):
    with pytest.raises(waveform_peaks.JobFailed, match='no longer on disk'):
        waveform_peaks.generate_waveform_peaks(str(tmp_path / 'gone.mkv'), 0)


def test_the_cache_evicts_the_least_recently_used_beyond_its_limit(queue):
    os.makedirs(waveform_peaks.PEAKS_CACHE_DIR)
    paths = []
    for index in range(5):
        path = os.path.join(waveform_peaks.PEAKS_CACHE_DIR, f'{index}.json')
        with open(path, 'wb') as f:
            f.write(b'x' * 100)
        os.utime(path, (1000 + index, 1000 + index))
        paths.append(path)
    in_progress = os.path.join(waveform_peaks.PEAKS_CACHE_DIR, '9.json.3.tmp')
    with open(in_progress, 'wb') as f:
        f.write(b'x' * 1000)
    os.utime(in_progress, (1, 1))
    # The oldest is the one just written, which must survive its own prune.
    waveform_peaks.prune_peaks_cache(max_bytes=250, keep=paths[0])

    remaining = sorted(os.listdir(waveform_peaks.PEAKS_CACHE_DIR))
    assert remaining == ['0.json', '4.json', '9.json.3.tmp']


class TestPeaksEndpoint:
    @staticmethod
    def _get(monkeypatch, video):
        monkeypatch.setattr(editor_api, '_resolve_or_abort', lambda: (video,))
        app = Flask(__name__)
        with app.test_request_context('/api/editor/peaks?mediaType=movie&mediaId=1&audioTrack=0'):
            return editor_api.EditorPeaks.get.__wrapped__(editor_api.EditorPeaks())

    def test_no_cache_answers_202_with_the_job(self, queue, monkeypatch, tmp_path):
        video = tmp_path / 'film.mkv'
        video.write_bytes(b'x')

        body, status = self._get(monkeypatch, str(video))

        assert status == 202
        assert body == {'jobId': queue.list_jobs_from_queue()[0]['job_id'], 'status': 'pending'}

    def test_cached_peaks_are_served_without_a_job(self, queue, monkeypatch, tmp_path):
        video = tmp_path / 'film.mkv'
        video.write_bytes(b'x')
        cached = {'peaks': [0.5, -1.0], 'duration': 0.2, 'sampleRate': 10}
        os.makedirs(waveform_peaks.PEAKS_CACHE_DIR)
        with open(waveform_peaks.peaks_cache_file(str(video), 0), 'w') as f:
            json.dump(cached, f)

        assert self._get(monkeypatch, str(video)) == cached
        assert queue.list_jobs_from_queue() == []
